apiVersion: v1
kind: PersistentVolume
metadata:
  name: bind-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/bind-pv-lab
    type: DirectoryOrCreate
