apiVersion: v1
data:
  license-key: NWVjdXIz
kind: Secret
metadata:
  name: app-license
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-demo
  name: secret-demo
spec:
  containers:
  - image: busybox
    name: secret-demo
    command: ["sleep", "300"]
    env:
    - name: LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: app-license
          key: license-key
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
