apiVersion: v1
data:
  ENVIRONMENT: dev
  PAGE_TITLE: ITI Kubernetes Lab
kind: ConfigMap
metadata:
  name: web-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-config-demo
  name: web-config-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-config-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: web-config-demo
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo \"$PAGE_TITLE $ENVIRONMENT\"; sleep 10; done"]
        envFrom:
        - configMapRef:
            name: web-config
        resources: {}
status: {}
