apiVersion: v1
data:
  index.html: |
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>ITI Volumes</title>
      </head>
      <body>
        <h1>ITI Volumes</h1>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: site-html
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-site
  name: nginx-site
spec:
  containers:
  - image: nginx:1.27
    name: nginx-site
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: html-volume
    configMap:
      name: site-html
status: {}
