apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpath-lab
  name: hostpath-lab
spec:
  containers:
  - image: busybox:1.36
    name: hostpath-lab
    command: ["sleep", "3600"]
    volumeMounts:
    - name: host-storage
      mountPath: /data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: host-storage
    hostPath:
      path: /tmp/hostpath-lab
      type: DirectoryOrCreate
status: {}
