apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
data:
  APP_TITLE: "ITI Notes"
  welcome.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ITI Notes</title>
    </head>
    <body>
        <h1>Welcome to ITI Notes Dashboard</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Secret
metadata:
  name: notes-secret
type: Opaque
stringData:
  admin-password: "super-secure-password"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: notes-app
spec:
  volumes:
  - name: config-volume
    configMap:
      name: notes-config
  - name: secret-volume
    secret:
      secretName: notes-secret
  - name: data-volume
    persistentVolumeClaim:
      claimName: notes-data
  containers:
  - name: web
    image: nginx:1.27
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html/index.html
      subPath: welcome.html
    - name: secret-volume
      mountPath: /etc/notes-secret
      readOnly: true
    - name: data-volume
      mountPath: /usr/share/nginx/html/data
  - name: agent
    image: busybox:1.36
    command: ["/bin/sh", "-c", "while true; do date -Iseconds >> /data/heartbeat.log; sleep 10; done"]
    volumeMounts:
    - name: data-volume
      mountPath: /data
