apiVersion: v1
kind: PersistentVolume
metadata:
  name: quiz-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /tmp/quiz-pv
    type: DirectoryOrCreate
